#### Importing packages

In [4]:
import numpy as np 
import pandas as pd

In [5]:
import sklearn.impute
from sklearn import preprocessing

In [6]:
df = pd.read_csv('datasets/Salaire.csv')
df

    AnneesExpérience   Salaire
0                1.1   39343.0
1                1.3   46205.0
2                1.5   37731.0
3                2.0   43525.0
4                2.2   39891.0
5                2.9   56642.0
6                3.0   60150.0
7                3.2   54445.0
8                3.2   64445.0
9                3.7   57189.0
10               3.9   63218.0
11               4.0   55794.0
12               4.0   56957.0
13               4.1   57081.0
14               4.5   61111.0
15               4.9   67938.0
16               5.1   66029.0
17               5.3   83088.0
18               5.9   81363.0
19               6.0   93940.0
20               6.8   91738.0
21               7.1   98273.0
22               7.9  101302.0
23               8.2  113812.0
24               8.7  109431.0
25               9.0  105582.0
26               9.5  116969.0
27               9.6  112635.0
28              10.3  122391.0
29              10.5  121872.0

#### Affichage des premier lignes

In [7]:
df.head()

   AnneesExpérience  Salaire
0               1.1  39343.0
1               1.3  46205.0
2               1.5  37731.0
3               2.0  43525.0
4               2.2  39891.0

In [8]:
# définition de la variable de scaler pour la normalisation en utilisant Min-Max
scaler = preprocessing.MaxAbsScaler()

#Transformation des données 
scaled = scaler.fit_transform(df)

In [9]:
scaler

MaxAbsScaler()

In [10]:
print (scaled )

[[0.1047619  0.32145337]
 [0.12380952 0.37751959]
 [0.14285714 0.30828247]
 [0.19047619 0.35562255]
 [0.20952381 0.32593083]
 [0.27619048 0.46279547]
 [0.28571429 0.49145771]
 [0.3047619  0.4448448 ]
 [0.3047619  0.52655015]
 [0.35238095 0.46726475]
 [0.37142857 0.51652491]
 [0.38095238 0.45586685]
 [0.38095238 0.46536919]
 [0.39047619 0.46638233]
 [0.42857143 0.49930959]
 [0.46666667 0.55508984]
 [0.48571429 0.53949228]
 [0.5047619  0.67887345]
 [0.56190476 0.66477927]
 [0.57142857 0.7675401 ]
 [0.64761905 0.74954858]
 [0.67619048 0.80294303]
 [0.75238095 0.82769158]
 [0.78095238 0.92990498]
 [0.82857143 0.89410986]
 [0.85714286 0.86266147]
 [0.9047619  0.95569936]
 [0.91428571 0.92028826]
 [0.98095238 1.        ]
 [1.         0.99575949]]